arenadata/adcm

- Makefile
used ci.arenadata.io/adcm:latest image to have django installed, same as others python dependencies
> CI-238 Added "make django_tests"

- tests/base/run_test.sh
fix for
```bash
+ TEST_CASE=
+ [[ !=  ]]
sh: : unknown operand
```
>  fix run_test.sh

- Dockerfile
- Makefile
- requirements.txt
Besides there are small changes in ansible and
all other packages from Alpine and Python 3.
> Bump base image to new Django 3

- web/karma.conf.js
- web/src/app/core/api/api.service.ts
- web/src/app/core/services/detail.service.ts
- web/src/app/core/types/api.ts
- web/src/app/shared/add-component/add-button.component.ts
- web/src/app/shared/add-component/add.service.ts
- web/src/app/shared/add-component/host.component.ts
- web/src/app/shared/add-component/host2cluster.component.ts
- web/src/app/shared/components/actions/actions.directive.spec.ts
- web/src/app/shared/components/actions/actions.directive.ts
- web/src/app/shared/components/list/base-list.directive.ts
- web/src/app/shared/components/list/list.component.html
- web/src/app/shared/components/list/list.component.ts
- web/src/app/shared/components/list/list.service.ts
- web/src/app/shared/directives/infinity-scroll.directive.ts
- drop down in forms of adding
- drop down in lists
> ADCM-1154  infinite scrolling everywhere

- pytest.sh
- python/adcm/settings.py
- requirements-test.txt
- tests/conftest.py
- tests/ui_tests/app/app.py
- tests/ui_tests/app/pages.py
- tests/ui_tests/test_activatable_groups_ui_options.py
- tests/ui_tests/test_configs.py
- tests/ui_tests/test_ro_fields_ui_options.py
Add retrying lib for retry on exception.
> Fix flaky on save button status.

- web/src/app/core/types/host-component.ts
- web/src/app/shared/host-components-map/dependencies.component.spec.ts
- web/src/app/shared/host-components-map/much-2-many/much-2-many.component.html
- web/src/app/shared/host-components-map/much-2-many/much-2-many.component.ts
- web/src/app/shared/host-components-map/take.service.spec.ts
- web/src/app/shared/host-components-map/take.service.ts
- web/src/app/shared/host-components-map/types.ts
Implement service/component dependency tree
> ADCM-1289 fixed constraints bug

- web/src/app/shared/details/detail.component.ts
- web/src/app/shared/details/left/left.component.ts
I fixed child object display issues (service was displaying cluster issue)
> ADCM-1380 issue on the child object

- Dockerfile
- Makefile
> Bump versions of Apline and python pkgs

- tests/ui_tests/app/configuration.py
Workaround for https://ci.arenadata.io/job/PR-builder-adcm_client/262/allure/#suites/afcb7b61652654a588a09f9817ba0a9f/d7b2e92b1c330614/
> Increase wait timeout for "conf is loaded" marker

- python/cm/upgrade.py
(if it does not exist in new prototypes)
> ADCM-1507 remove existing import on upgrade

- tests/functional/test_locked_objects.py
- tests/functional/test_locked_objects_data/host_bundle_on_any_level/hosts/ssh-host/ansible/locker-fast.yaml
- tests/functional/test_locked_objects_data/host_bundle_on_any_level/hosts/ssh-host/config.yaml
Remove deprecated action_run calls from test_locked_objects.py
> Add fast action for lock testing

- tests/functional/test_actions_on_host.py
- tests/functional/test_backend_filtering.py
- tests/functional/test_config.py
- tests/functional/test_custom_log_plugin.py
- tests/functional/test_delete_service_plugin.py
- tests/functional/test_events.py
- tests/functional/test_inventories.py
- tests/functional/test_locked_objects.py
- tests/functional/test_multijob.py
- tests/functional/test_nullable_fields.py
- tests/functional/test_sdk.py
Remove action_run calls
Remove yaml.load
> Fix test setup durations and refactoring

- python/cm/job.py
Time display format:  "Thursday 29 April 2021  10:58:26 +0000 (0:00:00.157)       0:00:00.157"
> ADCM-1679/ADCM-1703 Added timing to job log by default

- web/src/app/admin/users/users.component.html
- web/src/app/admin/users/users.component.scss
- web/src/app/admin/users/users.component.ts
Form was displayed outside viewport
>  ADCM-1812 fixed bug with "user add" card. 

- python/cm/signal_callbacks.py
- python/cm/status_api.py
- python/cm/unit_tests/test_signal_callbacks.py
- python/cm/unit_tests/utils.py
DB connection could be unavailable in moment when concern_change may be called
> FIX concern_change event handler

- tests/functional/test_locked_objects.py
- tests/functional/test_multijob.py
- tests/functional/test_plugins_host.py
Now used `locked` attribute instead of state changes
> ADCM-2055 actualize lock tests

- tests/functional/plugin_utils.py
- tests/functional/test_plugins_config.py
- tests/functional/test_plugins_config_data/cluster/component.yaml
- tests/functional/test_plugins_config_data/cluster/component_first.yaml
- tests/functional/test_plugins_config_data/cluster/component_first_service_first.yaml
- tests/functional/test_plugins_config_data/cluster/component_first_service_second.yaml
- tests/functional/test_plugins_config_data/cluster/component_second.yaml
- tests/functional/test_plugins_config_data/cluster/component_second_service_first.yaml
- tests/functional/test_plugins_config_data/cluster/component_second_service_second.yaml
- tests/functional/test_plugins_config_data/cluster/config.yaml
- tests/functional/test_plugins_config_data/cluster/first_service.yaml
- tests/functional/test_plugins_config_data/cluster/second_service.yaml
- tests/functional/test_plugins_config_data/provider/config.yaml
- tests/functional/test_plugins_config_data/provider/host.yaml
- tests/functional/test_plugins_config_data/provider/host_from_provider.yaml
- tests/functional/test_plugins_multi_state_set_unset.py
- tests/functional/test_plugins_multi_state_set_unset_data/provider/config.yaml
- tests/functional/test_plugins_state.py
Rework of tests and modernization of utilities for testing similar plugins
> ADCM-1911 rework of adcm_config plugin tests

- web/src/app/abstract-directives/adwp-base-list.directive.ts
> [ADCM-2078] per page item count for new users was fixed 

- tests/functional/test_config_after_upgrade.py
- tests/functional/test_config_after_upgrade_data/cluster_for_upgrade_with_configs_with_new_fields/config.yaml
- tests/functional/test_config_after_upgrade_data/cluster_for_upgrade_with_group_configs_with_new_fields/config.yaml
- tests/functional/test_config_after_upgrade_data/provider_for_upgrade_with_configs_with_new_fields/config.yaml
- tests/functional/test_config_after_upgrade_data/provider_for_upgrade_with_group_configs_with_new_fields/config.yaml
Also update tests for new fields in config
> ADCM-2171 pre Add xfail on test_upgrade_provider/cluster_with_group_configs

- tests/ui_tests/app/page/common/base_page.py
- tests/ui_tests/app/page/common/configuration/page.py
- tests/ui_tests/utils.py
Fix was made by changing the logic of underlying functions working with UI data and inputs
> Fix flaky tests: `test_custom_name_config` and `test_invoker_object_url`

- requirements-test.txt
- tests/functional/test_backend_filtering.py
- tests/library/errorcodes.py
Now soft asserts is more readable, no more colored errors
> ADCM-2237 replace delayed-assert to pytest-check

- python/cm/unit_tests/utils.py
changes was useful for inventory debug, so I committed them just in case
> minor fix for cm.unit_tests.utils

- tests/ui_tests/app/page/common/base_page.py
- tests/ui_tests/app/page/common/configuration/fields.py
- tests/ui_tests/app/page/common/configuration/locators.py
- tests/ui_tests/app/page/common/configuration/page.py
- tests/ui_tests/test_ui_config_hell.py
- tests/ui_tests/test_ui_config_hell_data/cluster_bundle/config_new_hell_service/config.yaml
Updated "old" config hell by giving it more "clear" names
Rewrote check of names displayed (actually groups)
Less required fields to achieve adequate test execution time
Autofill of required fields
Save button is pressed after config is loaded and all required fields are filled
> Click on "Save" button added to new "config hell" test

- tests/api/steps/asserts.py
- tests/api/testdata/db_filler.py
- tests/api/utils/data_classes.py
- tests/api/utils/endpoints.py
- tests/api/utils/types.py
Add rbac group draft endpoint
Fix patch data preparing on methods. Now PATCH body contains only changeable fields instead of full body
> ADCM-2356 Add rbac user endpoint

- tests/api/conftest.py
- tests/api/test_body/__init__.py
- tests/api/test_body/test_post.py
- tests/api/testdata/db_filler.py
- tests/api/utils/data_classes.py
- tests/api/utils/endpoints.py
- tests/api/utils/types.py
- tests/functional/test_events.py
Add new field type - password
Fix body checks - add password support and disable fk checks
Fix recursive test data generation
> ADCM-2371 enable /rbac/group endpoint api tests

- tests/api/utils/data_classes.py
- tests/api/utils/types.py
Fix negative values on some of field types
> ADCM-2425 add username field with more restrict rules

- pytest.sh
- python/rbac/upgrade/role_spec.yaml
- tests/functional/rbac/conftest.py
- tests/functional/rbac/test_adcm_related_permissions.py
- tests/functional/rbac/test_built_in_roles_composition.py
- tests/functional/rbac/test_cluster_related_permissions.py
- tests/functional/rbac/test_object_parametrization.py
- tests/functional/rbac/test_permissions_deleting.py
Fix test user client instance
Fix duplicate objects on roles checks
ADCM-2454 add "Edit infrastructure configurations" role to Provider Administrator
Fix typos in role spec
> ADCM-2525 actualize tests on application and infrastructure roles

- tests/ui_tests/app/locators.py
- tests/ui_tests/app/page/common/popups/locator.py
- tests/ui_tests/test_adcm_upgrade.py
- web/src/app/app.module.ts
- web/src/app/components/error-snack-bar/error-snack-bar.component.ts
- web/src/app/components/snack-bar/snack-bar.component.ts
- web/src/app/core/http-interseptors/auth-interseptor.ts
- web/src/app/core/services/app/app.service.ts
- web/src/app/core/services/channel.service.ts
> ADCM-1932 an error message model refactored. If the error message contains 'args' then show one

- tests/api/test_body/__init__.py
- tests/api/testdata/db_filler.py
- tests/api/utils/data_classes.py
- tests/api/utils/data_synchronization.py
- tests/api/utils/endpoints.py
- tests/functional/rbac/conftest.py
- tests/functional/rbac/test_adcm_related_permissions.py
- tests/functional/rbac/test_built_in_roles_composition.py
- tests/functional/rbac/test_business_permissions_data/cluster/config.yaml
- tests/functional/rbac/test_cluster_related_permissions.py
- tests/functional/rbac/test_object_parametrization.py
- tests/functional/tools.py
- tests/ui_tests/app/page/admin/page.py
fixup tests on new requirements
> ADCM-2450 add hierarchy tests

- tests/api/utils/data_classes.py
- tests/functional/rbac/__init__.py
- tests/functional/rbac/conftest.py
- tests/functional/rbac/test_built_in_roles_composition.py
fixed role composition test
fixed labels on rbac tests
> ADCM-2549 add built_in field to users and groups

- tests/api/testdata/generators.py
- tests/api/utils/data_synchronization.py
- tests/functional/rbac/conftest.py
- tests/functional/rbac/test_object_parametrization.py
Fix test discovering warning
Fix extended `object` fields
> ADCM-2530 add test for service permission with cluster parametrization

- tests/functional/rbac/actions/bundles/cluster/config.yaml
- tests/functional/rbac/actions/test_role_composition.py
- tests/functional/rbac/actions/test_role_creation.py
- tests/functional/rbac/actions/test_run_actions.py
- tests/functional/rbac/actions/utils.py
- tests/library/errorcodes.py
Waiting for [the previous PR](https://github.com/arenadata/adcm/pull/1475) to be merged
> ADCM-2503 Permissions on host actions and policy creation based on roles with various types

- tests/functional/test_inventories.py
- tests/functional/test_inventories_data/cluster-inventory.json
- tests/functional/test_inventories_data/upgrade/new/config.yaml
- tests/functional/test_inventories_data/upgrade/old/config.yaml
- tests/functional/test_upgrade_cluster.py
- tests/functional/tools.py
Need to merge it for [client](https://github.com/arenadata/adcm_client/pull/107) to get merged
> ADCM-2574 Update tests according to `before_upgrade` field new requirements

- tests/functional/rbac/conftest.py
- tests/functional/rbac/test_built_in_roles_composition.py
Waiting for implementation details to be confirmed as correct ones
> ADCM-2650 Update tests on roles composition

- web/src/app/shared/configuration/services/field.service.ts
https://arenadata.atlassian.net/browse/ADCM-2679
> ADCM-2679 send __main_info not required too

- tests/ui_tests/app/page/cluster/page.py
- tests/ui_tests/app/page/common/base_page.py
- tests/ui_tests/app/page/component/page.py
- tests/ui_tests/app/page/host/page.py
- tests/ui_tests/app/page/provider/page.py
- tests/ui_tests/app/page/service/page.py
- tests/ui_tests/test_host_page.py
- tests/ui_tests/test_regression.py
- tests/ui_tests/test_regression_data/main_info/cluster/actions.yaml
- tests/ui_tests/test_regression_data/main_info/cluster/config.yaml
- tests/ui_tests/test_regression_data/main_info/cluster/info.txt
- tests/ui_tests/test_regression_data/main_info/provider/actions.yaml
- tests/ui_tests/test_regression_data/main_info/provider/config.yaml
- tests/ui_tests/test_regression_data/main_info/provider/info.txt
Merge after https://github.com/arenadata/adcm/pull/1611 (UI-back connection fixed)
> ADCM-2677 Test on correct display of object's description on detailed page after __main_info_upgrade

- web/src/app/abstract-directives/list.directive.ts
- web/src/app/components/cluster/host/cluster-host.component.ts
- web/src/app/components/host/host-list/host-list.component.ts
- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.html
- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.scss
- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.spec.ts
- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.ts
- web/src/app/core/types/api.ts
- web/src/app/factories/list.factory.ts
- web/src/app/shared/components/list/base-list.directive.ts
- web/src/app/shared/components/list/list.service.ts
- web/src/app/shared/details/details.module.ts
Ticket - https://arenadata.atlassian.net/browse/ADCM-2770
> ADCM-2770 - UI: Add maintenance mode button to HOSTS page table view

- web/src/app/core/types/actions.ts
- web/src/app/shared/components/actions/action-list/menu-item/menu-item.component.ts
- web/src/app/shared/components/actions/actions.directive.spec.ts
- web/src/app/shared/components/actions/master/master.component.spec.ts
https://arenadata.atlassian.net/browse/ADCM-2778
> ADCM 2778 - Rework action list displaying logic

- web/src/adcm-theme.scss
- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.html
https://arenadata.atlassian.net/browse/ADCM-2813
> ADCM-2813 - Hosts page, the MM button becomes green when the host's row is selected

- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.html
- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.spec.ts
- web/src/app/components/maintenance-mode-button/maintenance-mode-button.component.ts
https://arenadata.atlassian.net/browse/ADCM-2814
> ADCM 2814 - Hosts page, the host's page opens up when the MM button is clicked

- web/src/app/shared/configuration/attributes/attributes/group-keys/group-keys-wrapper.component.ts
- web/src/app/shared/configuration/group-fields/group-fields.component.html
https://arenadata.atlassian.net/browse/ADCM-2856
> ADCM-2856 - Possibility to include config field in group-config with `config_group_customization=False` with `advanced: true` and not only

- web/src/app/shared/configuration/attributes/attribute-provider.component.ts
- web/src/app/shared/configuration/attributes/attributes/group-keys/group-keys-wrapper.component.ts
https://arenadata.atlassian.net/browse/ADCM-2851
> ADCM-2851 - Group config page, some group config fields get activated when clicking save

- web/src/app/shared/configuration/fields/fields.component.ts
- web/src/app/shared/configuration/main/config.component.html
- web/src/app/shared/configuration/main/config.component.spec.ts
- web/src/app/shared/configuration/main/config.component.ts
- web/src/app/shared/configuration/scheme/item.component.ts
- web/src/app/shared/configuration/services/field.service.ts
https://tracker.yandex.ru/ADCM-2865/files
> ADCM-2865 - Group config page, checkboxes' state doesn't get saved after clicking save

- web/src/app/shared/configuration/group-fields/group-fields.component.html
https://tracker.yandex.ru/ADCM-2424
Note: appTooltip(tooltip.directive.ts) seems to not working right at all. I suggest to fix it, or to stop using it, because matTooltip do it's job just right.
> ADCM-2424 - No tooltip for group on config page

- web/src/app/components/bell/bell.component.ts
- web/src/app/entry/task/tasks.component.ts
https://tracker.yandex.ru/ADCM-2913
> ADCM-2913 - Allow_to_terminate does not affect on action termination

- requirements-test.txt
- tests/functional/audit/__init__.py
- tests/functional/audit/conftest.py
- tests/functional/audit/scenarios/simple.yaml
- tests/library/audit/audit_log_schema.json
- tests/library/audit/checkers.py
- tests/library/audit/operations.py
- tests/library/audit/readers.py
> ADCM-2977 Tools for audit log testing

- web/src/app/shared/components/actions/actions.directive.ts
- web/src/app/shared/components/actions/master/master.component.html
- web/src/app/shared/components/actions/master/master.component.ts
- web/src/app/shared/components/upgrades/master/master.component.html
- web/src/app/shared/components/upgrades/master/master.component.ts
- web/src/app/shared/components/upgrades/upgrade.directive.ts
- web/src/app/shared/host-components-map/services2hosts/service-host.component.html
- web/src/app/shared/host-components-map/services2hosts/service-host.component.ts
https://tracker.yandex.ru/ADCM-2942
> ADCM-2942 - Action run is unavailable

- web/src/app/shared/components/upgrades/master/master.component.html
https://tracker.yandex.ru/ADCM-3006
> 3006 sonartest fix

- web/src/app/components/rbac/group-form/rbac-group-form.component.html
- web/src/app/components/rbac/group-form/rbac-group-form.component.ts
https://tracker.yandex.ru/ADCM-3014
> ADCM-3014 - Impossible to add ldap type user to local group

- python/cm/adcm_schema.yaml
- python/cm/models.py
- python/cm/upgrade.py
- tests/functional/test_concerns.py
- tests/functional/test_upgrade_cluster.py
- tests/functional/test_upgrade_hostprovider.py
https://tracker.yandex.ru/ADCM-3035
> ADCM-3035 Add multi_states to upgrade

- requirements-test.txt
- tests/functional/audit/bundles/create/cluster/config.yaml
- tests/functional/audit/bundles/create/incorrect_cluster/config.yaml
- tests/functional/audit/bundles/create/incorrect_provider/config.yaml
- tests/functional/audit/bundles/create/provider/config.yaml
- tests/functional/audit/conftest.py
- tests/functional/audit/scenarios/create_adcm_entities.yaml
- tests/functional/audit/scenarios/create_load_upload.yaml
- tests/functional/audit/scenarios/create_rbac_entities.yaml
- tests/functional/audit/scenarios/simple.yaml
- tests/functional/audit/test_create_operations_audit.py
- tests/functional/audit/test_operation_logs.py
- tests/library/audit/audit_log_schema.json
- tests/library/audit/checkers.py
- tests/library/audit/operations.py
- tests/library/audit/readers.py
Waiting for DENIED operation results and FAIL results during group config creation
> ADCM-2977 Tests on CREATE operations audit records

- web/src/app/shared/components/actions/action-list/menu-item/menu-item.component.ts
https://tracker.yandex.ru/ADCM-3012
> ADCM-3012: Hint absent for disabled adcm actions

- tests/functional/audit/conftest.py
- tests/functional/audit/scenarios/background_tasks.yaml
- tests/functional/audit/test_background_operations.py
- tests/functional/audit/test_rotation.py
- tests/functional/test_rotation.py
- tests/library/audit/operations.py
- tests/library/db.py
Merge after into ADCM-1524 after ADCM-3066
> ADCM-2980 Test on audit of background tasks

- tests/functional/audit/scenarios/full_update_rbac.yaml
- tests/functional/audit/test_update_rbac_objects.py
~~Blocked by https://tracker.yandex.ru/ADCM-3107~~
Blocked by https://tracker.yandex.ru/ADCM-3151
> ADCM-3093 Test on audit of changing all RBAC entities info

- tests/functional/audit/bundles/actions/cluster/actions.yaml
- tests/functional/audit/bundles/actions/cluster/config.yaml
- tests/functional/audit/bundles/actions/provider/actions.yaml
- tests/functional/audit/bundles/actions/provider/config.yaml
- tests/functional/audit/conftest.py
- tests/functional/audit/scenarios/cluster_actions.yaml
- tests/functional/audit/scenarios/provider_actions.yaml
- tests/functional/audit/test_actions_audit.py
- tests/library/audit/checkers.py
- tests/library/audit/operations.py
Blocked by https://tracker.yandex.ru/ADCM-3115
Blocked by https://tracker.yandex.ru/ADCM-3141
> ADCM-3029 Test on audit scenario of cluster and provider objects' actions

- tests/functional/ldap_auth/test_complex.py
- tests/functional/ldap_auth/test_sync.py
- tests/functional/rbac/test_users.py
- tests/ui_tests/test_admin_page.py
> ADCM-2582 Adjust tests for user deactivation

- tests/ui_tests/test_cluster_list_page.py
- web/src/app/components/concern/concern-item/concern-item.component.html
- web/src/app/components/concern/concern-item/concern-item.component.ts
- web/src/app/components/concern/concern.component.html
- web/src/app/components/concern/concern.component.ts
- web/src/app/models/concern/concern-reason.ts
https://tracker.yandex.ru/ADCM-2141
> ADCM-2141 - Concern link leads to object detailed page, but not to page with source of issue

- python/api/host/serializers.py
- python/api/host/views.py
- python/api/validators.py
- python/cm/tests/test_cluster.py
- python/cm/tests/test_host.py
Tasks done in here:
ADCM-3146
ADCM-3144
ADCM-3191
ADCM-3192
> ADCM-3146 Change returning errors during validation of cluster name update and host FQDN update + bugfixes

- web/src/app/shared/configuration/services/field.service.ts
https://tracker.yandex.ru/ADCM-3143
> ADCM-3143 - [UI] Fix config sending for group-configs
