Makefile
pytests are running in docker environment which is running from script of adcm repo that don`t inherit jenkins environment.
To fix need to set for container launch option -e BUILD_TAG=$BUILD_TAG.
For local launch we will have
```python
>> os.environ.get(BUILD_TAG)
''
```
which is still false in python
=> pytests ci containers label fix

Makefile
while building branch dependabot/go_modules/go/adcm/develop/github.com/stretchr/testify-1.4.0 make build fails with error
"invalid referance format"
this commit changes symbol / on _ in adcm image tag that is formed from branch name.
=> CI : fix container tag bug

api/stack_views.py
(change action type from list to read for /api/v1/stack/bundle/1/license/)
=> ADCM-965 fix coreapi schema for license api

conf/nginx/adcm.conf
There is a misconfiguration in adcm.conf which
lead to pass access logs to /var/log/nginx/if=0.
=> ADCM-1080 Fixup if=0 files in /var/log/nginx

requirements-test.txt
Supposed it is a bug in latest 5.3.3 pytest.
Failed: ScopeMismatch: You tried to access the 'function' scoped fixture 'expected_args' with a 'module' scoped request object, involved factories
tests/functional/test_backend_filtering.py:26:  def cluster_bundles(sdk_client_ms:adcm_client.objects.ADCMClient)
../usr/local/lib/python3.6/dist-packages/_pytest/fixtures.py:297:  def get_direct_param_fixture_func(request)
=> There is a strange issue with lazy fixture

Dockerfile, Makefile, requirements.txt
Upstream issue https://github.com/encode/django-rest-framework/issues/6203
was fixed so I think we can remove that restriction.
=> ADCM-270 Unfreeze markdown in requirements.txt

conf/nginx/adcm.conf
That commit force nginx to add nocache header to any static
file from wwwroot if we there is an nocache get paremeter
in uri. That is usefull for UI to contol caching.
=> Add nocache option to static files

python/cm/ansible_plugin.py, tests/functional/test_plugins_config.py, tests/functional/test_plugins_config_data/cluster/config.yaml, tests/functional/test_plugins_state.py, tests/functional/test_plugins_state_data/cluster/config.yaml
Last changes in e7476d8 has some regressions with context restriction in a number of ansible plugins.
It was a bug before ADCM-1143, that allow to use service_name in service context. While docs dissallow that, bundle writers used that.
That code allows to user service_name in service context.
=> ADCM-1166 Fixup wrong context for service_name

Dockerfile, Makefile, requirements.txt
That image bump adds patch to ansible for changing
package parameter type to list in apt_rpm module.
This patch was prepared by @amleshkov (lam@arenadata.io)
for community.general.
See https://github.com/ansible-collections/community.general/pull/169
=> ADCM-1229 apt_rpm: package as a list

conf/nginx/adcm.conf
While uploading large bundles we get 504 error.
Added timeout values for clien_body_timeout and api uwsgi_read_timeout
=> Change timeouts in nginx config

tests/ui_tests/app/configuration.py
There is no way for us to see password unencrypted anymore.
After this commit we stoped to check password field for equal,
because there is no way to read password back unecrypted.
We compare for empty only.
=> ADCM-1331 Fixup ui config test for password

web/src/app/app.component.ts
Without a space VERSION:2020.... looks ugly.
Hope it will brake nothing.
=> UI: add space after VERSION at footer

python/cm/job.py, python/cm/lock.py, python/cm/tests_job.py, python/cm/tests_runner.py, python/cm/unit_tests/utils.py, python/init_db.py, python/job_runner.py
- minor code reorder to group functions with similar responsibility
- rename object lock/unlock functions to hide realization from direct usage
- replace lock/unlock hierarchy function with generalized code
- TODO: locking mechanics remains the same for now
=> locks refactoring

Makefile
Fix alpine version in buildss target in Makefile: set image version to
golang:1.15-alpine3.13 because by defult image with alpine3.14 is used
and there is a bug with make in alpine3.14.
=> Fix alpine version in buildss

tests/ui_tests/app/app.py
New tab didn't open and didn't close in old implementation. send_keys method needs to get the input field, not a body. So changed to js command execution.
=> ADCM-1844_2 fix open and close tab in driver

.github/CODEOWNERS
Set Codeowners of the `functional` and `ui_tests` to @arenadata/python-qa so that Java QA will not be disturbed with the review requests
=> Set Codeowners of the `functional` and `ui_tests` to @arenadata/python-qa

requirements-test.txt, tests/api/steps/asserts.py, tests/api/test_body/test_patch.py, tests/api/test_body/test_post.py, tests/api/test_body/test_put.py, tests/api/testdata/db_filler.py, tests/api/testdata/generators.py, tests/api/utils/api_objects.py, tests/api/utils/data_classes.py, tests/api/utils/endpoints.py, tests/api/utils/fake_data.py, tests/api/utils/tools.py, tests/api/utils/types.py
- rethinking `relates_on`: now relates logic should be described for each `dataclass` field with relation
- now we check response body fields (assert that field is in body, values for created and changed fields)
- add new endpoints
=> ADCM-1949 Update CRUD tests for groups

requirements-test.txt, tests/functional/test_adcm_upgrade.py
Re-implemented fixture adcm_fs removed due to new upgradable ADCM flow (using `adcm_is_upgradable` fixture).
This PR is required to merge ADCM-1850 because of some other blocks in the plugin's changes.
=> Re-implemented fixture adcm_fs removed (Required for ADCM-1850)

python/adcm/settings.py, python/cm/errors.py
We have a HTTP 500 in case of integer overflow on SQLite.
This commit adds top level handler of OverFlow exception and
make an HTTP 400 response in such cases.
=> ADCM-2050 Intger overflow on DB save

pytest.sh, spec/objects.rst, tests/api/utils/data_classes.py
This commit adds config_id field to group-config endpoint.
config_id had been added to backend implementation in some
previous commits.
=> SPEC: TEST: add config_id to group-config

.gitignore, python/api/group_config/serializers.py, python/cm/models.py
This commit changes rules around config attribute on group-config. 
According to spec it should be readonly and non nullable.
=> ADCM-2053 config on group-config should be RO

python/cm/bundle.py
Hidden action role should be uniq for every bundle, prototype and
action.
So the name was changed to be the following:
<product name>_<product version>_<product edition>_<prototype type>_<prototype name>_<action display name>
=> ADCM-2418 ADCM-2414 extend name of action role

requirements-test.txt, tests/api/conftest.py, tests/api/testdata/getters.py, tests/conftest.py, tests/functional/conftest.py, tests/functional/test_adcm_upgrade.py, tests/functional/test_backend_filtering.py, tests/functional/test_config_groups.py, tests/pytest.ini, tests/ui_tests/conftest.py, tests/ui_tests/test_configs.py, tests/ui_tests/test_ui_config_hell.py
This PR is dedicated to speeding up "branch to develop" tests run.
To achieve it two things were done:
1. Some tests were marked as "full" because they take too much time or cover corner cases.
2. API tests were reworked to use "ADCM with dummy data" to skip the phase of pre-filling ADCM that takes about a minute for each test.
Also, the process of choosing which ADCM to use (clean or with dummy data) was reworked so it can be used in API tests the same way as it is used in functional and UI tests.
=> ADCM-2377 Speed up dev tests

requirements-test.txt, tests/functional/test_upgrade_cluster.py
Waiting for [this PR](https://github.com/arenadata/adcm_client/pull/107)
=> ADCM-2574 skip mark removed from `before_upgrade` upgrade tests

tests/base/test_api.py
We feel much pain when launches fail on this test for some reason, so I suggest silent this test for a while
=> Temporary skip flaky `test_task` unit test to decrease restarts during RBAC development

requirements-test.txt, tests/functional/rbac/actions/test_permissions_mixup.py, tests/functional/rbac/actions/test_run_actions.py, tests/functional/rbac/actions/test_upgrade.py, tests/functional/rbac/actions/utils.py, tests/functional/rbac/checkers.py, tests/functional/rbac/conftest.py, tests/functional/rbac/test_adcm_related_permissions.py, tests/functional/rbac/test_built_in_roles_composition.py, tests/functional/rbac/test_cluster_related_permissions.py, tests/functional/rbac/test_is_superuser.py, tests/functional/rbac/test_object_parametrization.py, tests/functional/rbac/test_permissions_deleting.py, tests/functional/rbac/test_reassignment.py, tests/functional/tools.py, tests/library/consts.py, tests/ui_tests/app/page/admin/page.py
Main changes:
- `is_denied` logic is changed to check permissions on interactions with objects directly via API, not via the client (ADCM client is checked the way it was)
- "user" objects are now received not at the start of the test and only those objects that are requested are the ones the user has permission for
Pay attention to:
- `is_denied` requires either ADCM client as `adcm_object` or ADCM object + client (by kwarg) to perform the correct check
- `is_allowed` operates only on "non-superuser" user objects it the alternative isn't set directly
=> ADCM-2648 Adopt tests for new RBAC view logic

Makefile, web/ng_test.sh
Update docker image for angular tests to run these test with node 16.
=> CI-1800 Update docker image for angular tests

python/audit/cases/cluster.py, python/audit/cases/service.py, python/audit/tests/test_cluster.py, tests/functional/audit/bundles/update/export/config.yaml, tests/functional/audit/bundles/update/import/config.yaml, tests/functional/audit/bundles/update/with_license/config.yaml, tests/functional/audit/bundles/update/with_license/text.txt, tests/functional/audit/conftest.py, tests/functional/audit/scenarios/cluster_updates.yaml, tests/functional/audit/scenarios/import_updates.yaml, tests/functional/audit/scenarios/plain_service_add.yaml, tests/functional/audit/test_cluster_objects_updates.py, tests/library/audit/operations.py
Blocked by https://tracker.yandex.ru/ADCM-3109
Blocked by ~~https://tracker.yandex.ru/ADCM-3111~~ https://tracker.yandex.ru/ADCM-3149
~~Blocked by https://tracker.yandex.ru/ADCM-3126~~
Blocked https://tracker.yandex.ru/ADCM-3150
=> ADCM-3028 Tests on audit of: import/binds, plain service add/remove, license accept, cluster-related updates
